spring:
  application:
    name: docextract

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: ci

---
spring:
  config:
    activate:
      on-profile: cluster
